### ISSUE TITLE
Failed to activate the tree-view-auto-reveal package

### ISSUE THREAD

**Issue by tjmehta** [stephan-evers/tree-view-auto-reveal#1]
[Enter steps to reproduce:]

1. Rebooted atom after receiving a package update.

**Atom**: 1.30.0 x64
**Electron**: 2.0.5
**OS**: Mac OS X 10.13.6
**Thrown From**: [tree-view-auto-reveal](https://github.com/stephan-evers/tree-view-auto-reveal) package 1.1.3

### Stack Trace

Failed to activate the tree-view-auto-reveal package

```
At Cannot read property 'isVisible' of undefined

TypeError: Cannot read property 'isVisible' of undefined
    at Object.activate (/packages/tree-view-auto-reveal/lib/tree-view-auto-reveal.js:16:25)
    at Package.activateNow (/Applications/AtomLite/Atom.app/Contents/Resources/app/src/package.js:230:33)
    at measure (/Applications/AtomLite/Atom.app/Contents/Resources/app/src/package.js:206:33)
    at Package.measure (/Applications/AtomLite/Atom.app/Contents/Resources/app/src/package.js:88:25)
    at activationPromise.Promise (/Applications/AtomLite/Atom.app/Contents/Resources/app/src/package.js:200:20)
    at new Promise (<anonymous>)
    at Package.activate (/Applications/AtomLite/Atom.app/Contents/Resources/app/src/package.js:198:38)
    at PackageManager.activatePackage (/Applications/AtomLite/Atom.app/Contents/Resources/app/src/package-manager.js:695:42)
    at config.transactAsync (/Applications/AtomLite/Atom.app/Contents/Resources/app/src/package-manager.js:670:36)
    at Config.transactAsync (/Applications/AtomLite/Atom.app/Contents/Resources/app/src/config.js:866:28)
    at PackageManager.activatePackages (/Applications/AtomLite/Atom.app/Contents/Resources/app/src/package-manager.js:668:23)
    at PackageManager.activate (/Applications/AtomLite/Atom.app/Contents/Resources/app/src/package-manager.js:647:50)
    at loadStatePromise.loadState.then (/Applications/AtomLite/Atom.app/Contents/Resources/app/src/atom-environment.js:875:27)
    at <anonymous>
```

### Commands

```
```

### Non-Core Packages

```
atom-better-tabname 1.6.0 
atom-clock 0.1.16 
atom-fuzzy-grep 0.17.2 
atom-ide-ui 0.13.0 
atom-sublime-monokai-syntax 0.4.4 
atom-unsaved-changes 0.4.0 
auto-detect-indentation 1.3.0 
autocomplete-modules 2.2.0 
busy-signal 1.4.3 
close-on-left 0.9.2 
custom-title 1.0.1 
Dependents 1.6.6 
docblockr 0.13.7 
fb-phabricator 0.0.0 
git-blame 1.7.0 
git-plus 8.1.0 
hey-pane 1.1.0 
highlight-selected 0.14.0 
hyperclick 0.0.0 
ide-flowtype 0.23.1 
intentions 1.1.5 
javascript-refactor 0.7.1 
js-hyperclick 1.13.3 
js-refactor 0.8.1 
line-diff-details-plus 1.9.1 
linter 2.2.0 
linter-eslint 8.4.1 
linter-flow 5.6.1 
linter-ui-default 1.7.1 
minimap 4.29.9 
minimap-bookmarks 0.4.2 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
multiline-tab 0.2.1 
open-git-modified-files 0.2.4 
open-on-phabricator 1.3.1 
prettier-atom 0.55.2 
quick-file-actions 0.2.2 
refactor 0.11.5 
tidy-tabs 0.4.0 
todo-show 2.3.2 
tree-view-auto-reveal 1.1.3 
```

**Comment by belgoros** [comment]
The same issue happens every time when a new project is opened, no matter either from a CLI or by using Atom `File-Open` menu.
```
The error was thrown from the tree-view-auto-reveal package. This issue has already been reported.
```
Atom version: `1.35.1`

**Comment by stephan-evers** [comment]
Thanks @johnschult for your fix. I've added your commit.
